name: Test Commit Message Clarity Rating

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  clarity-rating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Integration test
        uses: ./ # Uses an action in the root directory
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLAMA_URL: ${{ secrets.LLAMA_URL }}
